name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: unpmtu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm i

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
